import type { Metadata } from "next";
import LenisProvider from "../components/LenisProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        <LenisProvider>
          {children}
        </LenisProvider>
    
      </body>
    </html>
  );
}
